# Generated by Django 4.1.6 on 2023-02-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namning_app', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
